spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deploy
    username: root
    password: 1111

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  port: 8080
  serverAddress: localhost

serverName: local_server
